### ISSUE TITLE
화면을 세로로 길게 늘리면 fov가 이상해짐

### ISSUE THREAD

**Issue by mjy9088** [ft-vox/prototype-0#50]

**Comment by jeekpark** [comment]
와 신기하네요 ㅋㅋ
FOV가 X축으로 80이 고정되어있어서 세로가 길어지면 Y축 FOV가 180을 넘어가면서 뒤집어지는군요 

이론상 180도가 넘어가는 화면은 원근 투영으로는 불가능하고 등각투영이나 구면투영을 구현하기에는 화면이 게임스럽지 않고 이상하게 보일테니 180도가 넘지 않도록 제한을 걸어두어야겠군요

1. Y축 FOV가 120정도 넘어가면 고정을 시키든지
2. X축이든 Y축이든 상관없이 장축 기준으로 FOV를 80으로 고정시키든지(세로로 길어지면 세로축으로 80도 고정, 가로가 길어지면 가로축으로 80도 고정)

둘 중 하나로 고치면 될 것 같아요

**Comment by jeekpark** [comment]
3. 대각선 기준으로 80도 고정 (직각 삼각형에서 빗변은 직각의 변보다 항상 크니 X, Y축의 FOV는 항상 80보다 작음)

**Comment by mjy9088** [comment]
2번이 좋아보입니다!
